allow users to provide relative path in planckton flow root directory
cmelab/planckton-flow pull request #10
Opened 2021-05-28 21:23 UTC by jennyfothergill

fixes https://github.com/cmelab/planckton/issues/49

- provided path can be absolute path or relative path from planckton-flow root directory
- More descriptive error message

2021-06-09 21:08 UTC, JimmyRushing commented on src/project.py
> +            f"the COMOUND dictionary: {COMPOUND.keys()}\n"
did you mean compound silly goose?

2021-06-09 21:11 UTC, JimmyRushing commented on src/project.py
> +            f"the COMOUND dictionary: {COMPOUND.keys()}\n"
```suggestion
            f"the COMPOUND dictionary: {COMPOUND.keys()}\n"
```

2021-06-09 21:51 UTC, erjank commented
F the comound dictionary


On Wed, Jun 9, 2021 at 3:08 PM JimmyRushing ***@***.***>
wrote:

> *@JimmyRushing* commented on this pull request.
> ------------------------------
>
> In src/project.py
> <https://github.com/cmelab/planckton-flow/pull/10#discussion_r648686016>:
>
> > +        # this will be the path to the job e.g.,
> +        # path/to/planckton-flow/workspace/jobid
> +        dir_path = path.dirname(path.realpath(__file__))
> +        # this is the planckton root dir e.g.,
> +        # path/to/planckton-flow
> +        file_path = path.abspath(path.join(dir_path, "..", "..", "..", key))
> +        if path.isfile(key):
> +            print(f"Using {key} for structure")
> +            return key
> +        elif path.isfile(file_path):
> +            print(f"Using {file_path} for structure")
> +            return file_path
> +        raise FileNotFoundError(
> +            "Please provide either a path to a file (the absolute path or the "
> +            "relative path in the planckton-flow root directory) or a key to "
> +            f"the COMOUND dictionary: {COMPOUND.keys()}\n"
>
> did you mean compound silly goose?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmelab/planckton-flow/pull/10#pullrequestreview-680148957>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABIJRSXVTZYGARCDLCW5AA3TR7J6HANCNFSM45XPSPCQ>
> .
>

2021-06-09 22:40 UTC, JimmyRushing requested changes
It thought the relative path was "y6.mol2 /Users/jamesrushing/y6.mol2"

2021-06-10 00:04 UTC, jennyfothergill commented
> It thought the relative path was "y6.mol2 /Users/jamesrushing/y6.mol2"

Thanks for reviewing, @JimmyRushing! I had tested this before using signac operations but something about directly running the test_local file was different. 🤔 
Anyway, it's fixed now!

2021-06-10 18:48 UTC, JimmyRushing approved these changes
I ran with the absolute path and then i ran with only the relative path and it located the file both times.

2021-06-10 18:57 UTC, merged